python trainer_hard_negative.py \
    --bs 16 \
    --lr 0.001 \
    --epochs 30 \
    --gpu_id 0 \
    --checkpoint_path ./checkpoints/hard_negative \
    --image_type strip \
    --training_dataset_path ./MVTec_AD_dataset/grid_stripe/train/good/ \
    --img_format tiff \
    --num_defects_range 4 10 \
    --hard_negative_path ./MVTec_AD_dataset/hard_negatives/stripe_patterns/ \
    --hard_negative_ratio 0.2