python trainer.py \
    --bs 16 \
    --lr 0.001 \
    --epochs 30 \
    --gpu_id 0 \
    --checkpoint_path ./checkpoints/4channel \
    --image_type strip \
    --training_dataset_path ./MVTec_AD_dataset/grid_stripe_4channel/train/good/ \
    --img_format tiff \
    --num_defects_range 4 10