"""Convert fitted_theta.json (output of fit_real.py) to training yamls.

Three output flavors, all consumable by src_core/dataloader.py:PsfDefectPool
via search_trainer.py --psf_yaml_path:

  A. Individual  — one yaml per fitted real PSF in fitted/individual/. Each
                   yaml has zero-width [val, val] for every fitted dim, so a
                   pool draws from one fixed morphology with noise variations.
                   *** Local validation winner. Default emit. ***

  B. Aggregated  — single fitted/aggregated.yaml with [empirical_min, empirical_max]
                   per fitted dim. Lost the local A/B/C bake-off (uniform
                   sampling over the hull spends most draws in the gaps
                   between actual fits). Kept here for reproducibility but
                   not recommended.

  C. Clustered   — KMeans on the fitted theta vectors, K yamls in fitted/clusters/.
                   Per-cluster [mean - factor*std, mean + factor*std]. Local
                   validation showed a strong ceiling (best seed ~r@50 0.700)
                   but unstable: 1/3 seeds collapsed to r@50 = 0. Use only if
                   you have a multi-seed pool-pick mechanism downstream.

All three inherit non-fitted entries (brightness, background, gaussian_sigma,
intensity_abs, vector_mode, na, pol_type, etc.) from the base yaml verbatim.
Default --strategies emits A only; pass "ABC" to also generate B and C.
"""

import argparse
import json
import os
import sys

import numpy as np
import yaml
from sklearn.cluster import KMeans

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'src_core'))

from generate_psf import load_config as load_psf_config  # noqa: E402


DEFAULT_BASE_YAML = os.path.join(PROJECT_ROOT, 'src_core', 'defects', 'type4_vector.yaml')


def _load_base(base_yaml_path):
    """Load base yaml as plain dict (lists not tuples) so yaml.dump round-trips cleanly."""
    cfg = load_psf_config(base_yaml_path)
    plain = {}
    for k, v in cfg.items():
        if isinstance(v, tuple):
            plain[k] = list(v)
        else:
            plain[k] = v
    return plain


def _write_yaml(d, path, header_comment=None):
    with open(path, 'w') as f:
        if header_comment:
            for line in header_comment.splitlines():
                f.write(f'# {line}\n')
            f.write('\n')
        yaml.dump(d, f, sort_keys=False, default_flow_style=None)


def export_individual(fits, base, fit_param_names, out_dir, base_yaml_path):
    """Strategy A: one yaml per fitted PSF, each with zero-width ranges."""
    os.makedirs(out_dir, exist_ok=True)
    paths = []
    for defect_id, rec in fits.items():
        cfg = dict(base)
        for name in fit_param_names:
            v = float(rec['theta'][name])
            cfg[name] = [v, v]
        header = (f'Auto-generated by src_invertfit/export_yaml.py (Strategy A)\n'
                  f'Source: {defect_id}, fit residual_pp={rec["residual_l1_per_pixel"]:.3f}\n'
                  f'Fitted I={rec["I"]:.1f}, alpha=({rec["alpha1"]:.3f}, {rec["alpha2"]:.3f})\n'
                  f'Inherits non-fitted params from {os.path.basename(base_yaml_path)}')
        out_path = os.path.join(out_dir, f'{defect_id}.yaml')
        _write_yaml(cfg, out_path, header)
        paths.append(out_path)
    return paths


def export_aggregated(fits, base, fit_param_names, out_path, base_yaml_path,
                      pad_frac=0.05):
    """Strategy B: single yaml with [min - pad, max + pad] per fitted dim.

    pad_frac slightly extends the empirical hull (default ±5% of range) so the
    training pool can sample slightly outside the observed extremes. Set 0 for
    strict empirical bounds.
    """
    cfg = dict(base)
    rows = []
    for name in fit_param_names:
        vals = [rec['theta'][name] for rec in fits.values()]
        lo, hi = float(min(vals)), float(max(vals))
        if pad_frac > 0:
            span = hi - lo
            lo = lo - span * pad_frac
            hi = hi + span * pad_frac
        # Round to 4 decimals for readability
        lo, hi = round(lo, 4), round(hi, 4)
        cfg[name] = [lo, hi]
        rows.append((name, lo, hi))
    header = (f'Auto-generated by src_invertfit/export_yaml.py (Strategy B - aggregated)\n'
              f'{len(fits)} fits → empirical [min, max] per fitted dim '
              f'(pad ±{pad_frac*100:.0f}% of span)\n'
              f'Inherits non-fitted params from {os.path.basename(base_yaml_path)}')
    _write_yaml(cfg, out_path, header)
    return rows


def export_clusters(fits, base, fit_param_names, out_dir, base_yaml_path,
                    k=3, std_factor=1.0, seed=0):
    """Strategy C: KMeans into K groups, one yaml per cluster.

    Each yaml uses [center - std_factor * std, center + std_factor * std] per
    fitted dim, where std is computed within the cluster.
    """
    os.makedirs(out_dir, exist_ok=True)

    names = list(fit_param_names)
    X = np.array([[rec['theta'][n] for n in names] for rec in fits.values()],
                 dtype=np.float64)
    defect_ids = list(fits.keys())

    k_eff = min(k, len(defect_ids))
    if k_eff < 2:
        print(f'  [export_clusters] only {len(defect_ids)} fits, falling back to '
              f'aggregated single yaml')
        return []

    km = KMeans(n_clusters=k_eff, n_init=10, random_state=seed).fit(X)
    labels = km.labels_

    paths = []
    for c in range(k_eff):
        mask = labels == c
        members = [d for d, m in zip(defect_ids, mask) if m]
        if not members:
            continue
        Xc = X[mask]
        cfg = dict(base)
        for j, name in enumerate(names):
            mu = float(Xc[:, j].mean())
            sd = float(Xc[:, j].std()) if Xc.shape[0] > 1 else 0.0
            lo = round(mu - std_factor * sd, 4)
            hi = round(mu + std_factor * sd, 4)
            if lo == hi:  # zero-std (one-member cluster) → small fallback width
                hi = round(lo + 0.001, 4)
            cfg[name] = [lo, hi]
        header = (f'Auto-generated by src_invertfit/export_yaml.py (Strategy C - cluster {c+1}/{k_eff})\n'
                  f'KMeans members ({len(members)}): {", ".join(members)}\n'
                  f'Range per dim: cluster_mean ± {std_factor:.1f}*cluster_std\n'
                  f'Inherits non-fitted params from {os.path.basename(base_yaml_path)}')
        out_path = os.path.join(out_dir, f'cluster_{c+1:02d}.yaml')
        _write_yaml(cfg, out_path, header)
        paths.append(out_path)

    return paths


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--input_json', default='src_invertfit/fitted/fitted_theta.json',
                        help='Path to fitted_theta.json (output of fit_real.py).')
    parser.add_argument('--output_dir', default='src_invertfit/fitted',
                        help='Where to write individual/, aggregated.yaml, clusters/.')
    parser.add_argument('--base_yaml', default=DEFAULT_BASE_YAML,
                        help='Base yaml whose non-fitted params are inherited.')
    parser.add_argument('--k_clusters', type=int, default=3,
                        help='Number of clusters for Strategy C.')
    parser.add_argument('--std_factor', type=float, default=1.0,
                        help='Cluster yaml range width as ±std_factor * cluster_std.')
    parser.add_argument('--pad_frac', type=float, default=0.05,
                        help='Aggregated yaml hull padding (frac of span).')
    parser.add_argument('--strategies', type=str, default='A',
                        help='Subset of strategies to emit. Default "A" (the only '
                             'one that survived local A/B/C validation). '
                             'Pass "ABC" or "AC" to also generate B/C for analysis.')
    parser.add_argument('--seed', type=int, default=0)
    args = parser.parse_args()

    with open(args.input_json) as f:
        data = json.load(f)
    fits = data['fits']
    fit_param_names = data['meta']['fit_param_names']
    print(f'Loaded {len(fits)} fits from {args.input_json}')
    print(f'Fitted dims: {fit_param_names}')

    base = _load_base(args.base_yaml)
    print(f'Base yaml: {args.base_yaml}')
    print(f'Output dir: {args.output_dir}\n')

    os.makedirs(args.output_dir, exist_ok=True)

    if 'A' in args.strategies.upper():
        out_dir = os.path.join(args.output_dir, 'individual')
        paths = export_individual(fits, base, fit_param_names, out_dir, args.base_yaml)
        print(f'[A] Wrote {len(paths)} individual yamls to {out_dir}/')

    if 'B' in args.strategies.upper():
        out_path = os.path.join(args.output_dir, 'aggregated.yaml')
        rows = export_aggregated(fits, base, fit_param_names, out_path,
                                 args.base_yaml, pad_frac=args.pad_frac)
        print(f'[B] Wrote {out_path}')
        print(f'    Empirical ranges (with ±{args.pad_frac*100:.0f}% pad):')
        for name, lo, hi in rows:
            print(f'      {name:<12s}: [{lo:>8.4f}, {hi:>8.4f}]')

    if 'C' in args.strategies.upper():
        out_dir = os.path.join(args.output_dir, 'clusters')
        paths = export_clusters(fits, base, fit_param_names, out_dir,
                                args.base_yaml, k=args.k_clusters,
                                std_factor=args.std_factor, seed=args.seed)
        print(f'[C] Wrote {len(paths)} cluster yamls to {out_dir}/')


if __name__ == '__main__':
    main()
