"""Visualize raw PSF patches generated by create_psf_defect() for a single type."""

import sys
import os
import argparse
import numpy as np
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src_core'))
from generate_psf import load_config, create_psf_defect


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--psf_type', type=str, required=True,
                        help='PSF type name (e.g., type1)')
    parser.add_argument('--output_dir', type=str, default='../output')
    parser.add_argument('--n_samples', type=int, default=10)
    args = parser.parse_args()

    defects_dir = os.path.join(os.path.dirname(__file__), '..', 'src_core', 'defects')
    os.makedirs(args.output_dir, exist_ok=True)

    cfg = load_config(os.path.join(defects_dir, f'{args.psf_type}.yaml'))

    patches = []
    attempts = 0
    while len(patches) < args.n_samples and attempts < args.n_samples * 10:
        p = create_psf_defect(cfg)
        attempts += 1
        if p is not None:
            patches.append(p)

    n = len(patches)
    fig, axes = plt.subplots(2, n, figsize=(3 * n, 6), dpi=200)

    for i, patch in enumerate(patches):
        h, w = patch.shape
        axes[0, i].imshow(patch, cmap='hot', vmin=0, vmax=1, interpolation='nearest')
        axes[0, i].set_title(f'{h}x{w}', fontsize=11)
        axes[0, i].axis('off')

        binary = (patch > 0.1).astype(np.float32)
        axes[1, i].imshow(binary, cmap='gray', vmin=0, vmax=1, interpolation='nearest')
        axes[1, i].set_title(f'mask: {int(binary.sum())}px', fontsize=10)
        axes[1, i].axis('off')

    fig.text(0.01, 0.75, 'PSF', fontsize=12, va='center', rotation=90)
    fig.text(0.01, 0.3, 'Mask', fontsize=12, va='center', rotation=90)
    plt.suptitle(f'PSF Patches — {args.psf_type}', fontsize=14)
    plt.tight_layout(rect=[0.02, 0, 1, 0.95])

    out_path = os.path.join(args.output_dir, f'psf_patch_{args.psf_type}.png')
    plt.savefig(out_path, dpi=200, bbox_inches='tight')
    plt.close()
    print(f'Saved: {out_path}')


if __name__ == '__main__':
    main()
